export const PRICING_PLANS = [
  {
    id: "starter",
    name: "Starter",
    monthlyPrice: 29,
    annualPrice: 23,
    description: "For smart developers",
    cta: "Start Free Trial",
    ctaType: "outline" as const,
    popular: false,
    features: [
      "1 Project",
      "5 Agents",
      "Booking management",
      "Basic reports",
      "Email support",
    ],
  },
  {
    id: "business",
    name: "Business",
    monthlyPrice: 79,
    annualPrice: 63,
    description: "For growing companies",
    cta: "Book a Live Demo",
    ctaType: "solid" as const,
    popular: true,
    features: [
      "Unlimited Projects",
      "25 Agents",
      "Commission automation",
      "Approval workflow",
      "Revenue analytics",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    monthlyPrice: 100,
    annualPrice: 80,
    description: "For large companies",
    cta: "Start Free Trial",
    ctaType: "outline" as const,
    popular: false,
    features: [
      "Unlimited Agents",
      "Multiple teams",
      "Dedicated onboarding",
      "Advanced reports",
      "Account manager",
    ],
  },
];
